# Generated by Django 3.2.16 on 2022-12-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartRecipe',
        ),
    ]
