# Generated by Django 3.2.16 on 2022-12-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', verbose_name='Изображение блюда'),
        ),
    ]
