# Generated by Django 3.2.16 on 2022-12-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
